### ISSUE TITLE
CSS Style

### ISSUE THREAD

**Issue by zachfedor** [MelonsAway/more-css-practice#6]
https://github.com/MelonsAway/more-css-practice/blob/9b71d30515c89da42983e5919f8ca734b4e49215/instagram/styles.css#L2-L7

This isn't wrong, but you can save yourself the trouble of trying to line up your closing bracket along the same column as the opening one. Most style guides recommend having them like this:

```css
.nav {
   float: left;
}
.nolist {
   list-style-type: none;
}
```
